source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '~> 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '~> 3.3.0'
  gem 'listen', '>= 2.7', '< 4.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# 2017/06/24 enable the format of XML
gem 'activemodel-serializers-xml'
gem 'bcrypt', '~>3.1.7'

# 2017/08/05 scraping
gem 'mechanize'

# 2017/09/07 sign up and login
gem 'devise'

# 2017/11/06 デバッグ出力の整形
gem 'awesome_print', :group => [:development, :test]

#2017/12/02 环境设定 .env
gem 'dotenv-rails'

#2018/02/07 jQuery
gem "jquery-rails"

#2018/03/24 bootstrap
# gem 'sass-rails', '~> 5.0' # 已经有了
gem 'bootstrap-sass'


# 2018/03/31 整合model和view的中间逻辑
gem 'active_decorator'

# 2019/02/27 paging
gem 'kaminari'
# 2019/02/27 合并到一起
group :development, :test do
  # 2018/03/31 把model的列数据写入model文件
  gem 'annotate'

  # 2018/03/31 console的输出改用pry (默认的irb太难看)
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'pry-stack_explorer'

  # 2018/04/18 rails console 表格输出 model
  gem 'hirb'         # 出力結果を表として出力するgem
  gem 'hirb-unicode'  # マルチバイト文字の表示を補正するgem
  gem 'unicode-display_width', '~> 0.1.1'

  # 2019/02/27 解决SQL的N+1请求
  gem 'bullet'

  # 2019/02/27 验证代码
  # gem "rubocop", "~> 0.49.0", require: false

  # 2019/02/27 erd图
  gem 'rails-erd'
end
