source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Declare your gem's dependencies in blorgh.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# fix Could not find server ''
# https://stackoverflow.com/questions/63811244/rails-will-not-run-server
# gem 'webrick', '~> 1.7'
gem 'puma', '~> 5.2'

# To use a debugger
# gem 'byebug', group: [:development, :test]
